// This file lives ONLY on the server. Correct answers and model summaries
// are stripped out before anything is sent to a regular staff member.
// See server.js: /api/questions vs /api/admin/submissions/:id.

module.exports = [
  // ---- Section 1: Punishment Guide (multiple choice) ----
  { id: "p1", section: "Punishment Guide", type: "mc",
    q: "A player commits RDM (Random Deathmatch) for the first time. What's the correct punishment?",
    options: ["Verbal Warning", "Written Warning", "15 Minute Kick", "Temporary Ban"], correct: 1,
    note: "Core In-Game offense. Starts at Written Warning and escalates to a temp ban (1 week) by the 4th offense." },
  { id: "p2", section: "Punishment Guide", type: "mc",
    q: "A player is caught Meta Gaming for the first time.",
    options: ["Written Warning", "15 Minute Kick", "Extended Kick", "Permanent Ban"], correct: 0,
    note: "Same escalation ladder as RDM/VDM, starting with a Written Warning." },
  { id: "p3", section: "Punishment Guide", type: "mc",
    q: "A player is RPing without staff-approved permission for the first time.",
    options: ["Verbal Warning", "Written Warning", "15 Minute Kick", "Extended Kick"], correct: 0,
    note: "One of the few offenses that starts at Verbal rather than Written Warning." },
  { id: "p4", section: "Punishment Guide", type: "mc",
    q: "A player is caught running a scene from the Banned Roleplays list.",
    options: ["Written Warning", "Extended Kick", "Temporary Ban", "Permanent Ban"], correct: 3,
    note: "Banned Roleplays are strictly banned with no excuse, so this is an instant Permanent Ban." },
  { id: "p5", section: "Punishment Guide", type: "mc",
    q: "A player uses a racial slur / engages in racism.",
    options: ["Extended Kick", "Temporary Ban (2 weeks)", "Permanent Ban", "Written Warning"], correct: 2,
    note: "Server Safety Disruption. Instant Permanent Ban, no warnings issued first." },
  { id: "p6", section: "Punishment Guide", type: "mc",
    q: "A player is caught exploiting.",
    options: ["Temporary Ban", "Permanent Ban", "Extended Kick", "30 Minute Kick"], correct: 1,
    note: "Same tier as Racism and Breaking Roblox ToS. Instant Permanent Ban." },
  { id: "p7", section: "Punishment Guide", type: "mc",
    q: "A player uses an unauthorized Default Livery on patrol for the first time.",
    options: ["Verbal Warning", "15 Minute Kick", "30 Minute Kick", "Temporary Ban"], correct: 1,
    note: "Starts at a 15 Minute Kick, escalating to a temp ban by the 3rd/4th offense." },
  { id: "p8", section: "Punishment Guide", type: "mc",
    q: "A staff member commits Staff RDM for the first time.",
    options: ["Written Warning", "15 Minute Kick", "Temporary Ban (2 weeks)", "Permanent Ban"], correct: 2,
    note: "Judged more harshly than regular RDM. 2-week temp ban on the first offense, Permanent Ban on the 2nd." },
  { id: "p9", section: "Punishment Guide", type: "mc",
    q: "A kicked player rejoins the server immediately, for the first time.",
    options: ["Written Warning", "Extended Kick", "Temporary Ban (1 week)", "Permanent Ban"], correct: 2,
    note: "Rejoining After a Kick starts at a 1-week temp ban." },
  { id: "p10", section: "Punishment Guide", type: "mc",
    q: "A player is caught trolling (first offense).",
    options: ["Written Warning", "15 Minute Kick", "Extended Kick", "Temporary Ban"], correct: 2,
    note: "Trolling skips straight to an Extended Kick on the first offense." },

  // ---- Section 2: Procedures & Permissions (written answer) ----
  { id: "k1", section: "Procedures & Permissions", type: "scenario",
    q: "Before granting Hostage/Kidnapping RP perms, what MUST you check?",
    modelSummary: "A good backstory and sensible scenario, plus confirmation that an Administrator is available to supervise the scene. It shouldn't be approved when you're the only staff on duty or during high call load. Backstory alone isn't enough; supervision coverage is a hard requirement." },
  { id: "k2", section: "Procedures & Permissions", type: "scenario",
    q: "How do you properly log an approved roleplay scene?",
    modelSummary: "Use the /roleplay log command, providing the players involved, the location, and the duration. All approved roleplays need to be logged this way." },
  { id: "k3", section: "Procedures & Permissions", type: "scenario",
    q: "What's the max duration for a Priority Timer or Peace Timer?",
    modelSummary: "10 minutes (600 seconds) at a time, for either timer." },
  { id: "k4", section: "Procedures & Permissions", type: "scenario",
    q: "The server is in a wave of RDM/VDM and you need to pause criminal activity entirely. Which command do you use, and what do you announce?",
    modelSummary: "The Peace Timer, :pt [time], for example :pt 300, with the announcement 'A peace timer has been set. All criminal activity such as robberies is paused.' The Priority Timer (:prty) is different: it only cuts back on disruptive behavior without pausing criminal activity outright." },
  { id: "k5", section: "Procedures & Permissions", type: "scenario",
    q: "For a witness-based ban request to count as valid evidence, how many independent, non-biased witnesses are required?",
    modelSummary: "Three or more independent witnesses, with no conflict of interest or friendship between them." },
  { id: "k6", section: "Procedures & Permissions", type: "scenario",
    q: "A Moderator believes a ban is warranted. What's the correct process?",
    modelSummary: "Collect clear evidence and submit a /ban-request. Moderators can't issue bans directly; an Administrator has to review it and approve or deny it." },
  { id: "k7", section: "Procedures & Permissions", type: "scenario",
    q: "When is the :mod / :unmod command actually permitted?",
    modelSummary: "Only by Trial Administrators and above, and only during trainings. Trial Internal Affairs and above may also use :unmod specifically when processing terminations. It's tightly restricted, not a general-purpose command." },
  { id: "k8", section: "Procedures & Permissions", type: "scenario",
    q: "A regular Moderator uses :bring on a player while off duty, with no reason given. Is that allowed?",
    modelSummary: "No. Off-duty use of :bring is reserved for Internal Affairs investigating suspected staff misconduct. A regular Moderator using it off duty is itself a misuse-of-command issue worth flagging." },

  // ---- Section 3: Judgment Calls (written answer) ----
  { id: "s1", section: "Judgment Calls", type: "scenario",
    q: "You're currently moderating and you're the ONLY moderator on duty. Someone requests Hostage RP perms, providing a proper backstory and showing willingness to conduct the scene properly. Do you accept or deny this request? Explain your reasoning.",
    modelSummary: "Deny for now. A good backstory isn't sufficient on its own; an Administrator must be available to supervise the scene, and approving solo skips a hard requirement, not a soft one." },
  { id: "s2", section: "Judgment Calls", type: "scenario",
    q: "The server is flooding with pending mod calls, mass RDM/VDM is happening, and you're one of very few staff online. What's your immediate response, step by step?",
    modelSummary: "Flag High Load status, use /request staff for backup, then set a Peace Timer (:pt, max 600 seconds) with the required announcement. Use a Priority Timer instead if it's disruptive behavior rather than full criminal activity." },
  { id: "s3", section: "Judgment Calls", type: "scenario",
    q: "A player was kicked for Trolling. Ten minutes later they rejoin and immediately repeat the same behavior. What do you check before taking action, and what's the likely outcome?",
    modelSummary: "Check /player search for their punishment history. Two kickable offenses within a 3-hour window escalate the third automatically toward a temp ban, not back to a warning." },
  { id: "s4", section: "Judgment Calls", type: "scenario",
    q: "You witness a fellow Moderator use the teleport-to (:to) command on a player while off duty, with no clear reason given. What do you do?",
    modelSummary: "Report it to Internal Affairs or a Supervisor. Off-duty :to is restricted to Trial Internal Affairs+ investigating misconduct, so a regular Moderator using it is itself a red flag, not something to handle peer-to-peer." },
];
